apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: voting-app-demo
    name: postgres-service
spec:
  ports:
  - port: 5432
  selector:
    app: voting-app-demo
    name: postgres-pod