apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    app: voting-app-demo
    name: redis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app-demo
      name: redis-pod
  template:
    metadata:
      labels:
        app: voting-app-demo
        name: redis-pod
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379