apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: voting-app-demo
    name: result-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31001
  selector:
    app: voting-app-demo
    name: result-app-pod