apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    app: voting-app-demo
    name: result-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app-demo
      name: result-app-pod
  template:
    metadata:
      labels:
        app: voting-app-demo
        name: result-app-pod
    spec:
      containers:
      - name: result-app
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80