apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: voting-app-demo
    name: voting-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: voting-app-demo
    name: voting-app-pod