apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    app: voting-app-demo
    name: voting-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app-demo
      name: voting-app-pod
  template:
    metadata:
      labels:
        app: voting-app-demo
        name: voting-app-pod
    spec:
      containers:
      - name: voting-app
        image: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80